tuqulore/jumpu-ui

- packages/tailwindcss/index.js
- packages/tailwindcss/input.js
- packages/tailwindcss/lib/inputStyle.js
- packages/tailwindcss/select.js
- packages/tailwindcss/stories/Input.stories.mdx
- packages/tailwindcss/stories/LoginCard.stories.mdx
- packages/tailwindcss/stories/Select.stories.mdx
- packages/tailwindcss/stories/SignUpCard.stories.mdx
- packages/tailwindcss/stories/Textarea.stories.mdx
- packages/tailwindcss/textarea.js
> refactor: Input、Select、Textareaの整理

- LICENSE.md
- packages/tailwindcss/LICENSE.md
- packages/tailwindcss/NOTICE.md
> docs: add license, notice

- packages/tailwindcss/input.js
- packages/tailwindcss/select.js
- packages/tailwindcss/stories/FilledTag.stories.mdx
- packages/tailwindcss/stories/Input.stories.mdx
- packages/tailwindcss/stories/LoginCard.stories.mdx
- packages/tailwindcss/stories/Select.stories.mdx
- packages/tailwindcss/stories/SignUpCard.stories.mdx
- packages/tailwindcss/stories/Textarea.stories.mdx
- packages/tailwindcss/textarea.js
ref: #153 #155
- #155 で #153 への対応がもれていたことへの追従
- filled-tag の変更もれ
> feat: jumpu.prefix への追従

- packages/tailwindcss/tab.js
d0653f620b98e342983fff7473d8921370ab93a3 の変更漏れです
> fix(Tabs): theme function returns undefined

- packages/tailwindcss/accordion.js
- packages/tailwindcss/avatar.js
- packages/tailwindcss/badge.js
- packages/tailwindcss/balloon.js
- packages/tailwindcss/boxedTab.js
- packages/tailwindcss/button.js
- packages/tailwindcss/card.js
- packages/tailwindcss/filledTag.js
- packages/tailwindcss/iconButton.js
- packages/tailwindcss/input.js
- packages/tailwindcss/labeledLikeButton.js
- packages/tailwindcss/likeButton.js
- packages/tailwindcss/outlinedButton.js
- packages/tailwindcss/select.js
- packages/tailwindcss/spinner.js
- packages/tailwindcss/tab.js
- packages/tailwindcss/tag.js
- packages/tailwindcss/textButton.js
- packages/tailwindcss/textarea.js
- packages/tailwindcss/toggleSwitch.js
単一のオブジェクトでも受け付けられる
See: https://tailwindcss.com/docs/plugins#css-in-js-syntax
> refactor: 冗長なaddComponents()への配列指定

- packages/tailwindcss/.storybook/preview.js
- packages/tailwindcss/stories/Introduction.stories.mdx
> docs: rewrite introduction

- .github/workflows/ci.yaml
関連: https://github.com/tuqulore/jumpu-ui/pull/101#issuecomment-960457463
以前reviewdogを取り除いた際の変更もれ
> chore: reviewdogのgithub actionsを取り除く

- .github/workflows/deploy.yaml
- .gitignore
- .prettierignore
Storybookがより簡単に閲覧できるようにGitHub Pagesにデプロイする変更です
> chore: setup storybook github page deployment

- packages/tailwindcss/iconButton.js
- packages/tailwindcss/stories/IconButton.stories.mdx
> docs: IconButtonのツールチップの位置変更

- packages/tailwindcss/README.md
- packages/tailwindcss/colors.js
- packages/tailwindcss/stories/Color.stories.mdx
- packages/tailwindcss/tailwind.config.js
- packages/tailwindcss/theme.js
> feat: 色の整理

- packages/tailwindcss/stories/Card.stories.mdx
> docs(Card): Anchorであるときに必要に応じてdisplayプロパティ付与してほしい

- packages/tailwindcss/stories/Tag.stories.mdx
> docs(Tag): Anchor使用時の閉じるボタンとの併用は推奨しない

- packages/tailwindcss/stories/Input.stories.mdx
関連 https://github.com/tuqulore/jumpu-ui/issues/156
> refactor: h3をlabelにする

- packages/tailwindcss/stories/Tag.stories.mdx
https://github.com/tuqulore/jumpu-ui/pull/293#discussion_r1086070810 への対応です
> feat(Tag): drop aria-pressed

- package.json
> chore: set packageManager field

- .github/workflows/ci.yaml
> chore: drop set-output

- packages/tailwindcss/README.md
- packages/tailwindcss/accordion.js
- packages/tailwindcss/boxedTab.js
- packages/tailwindcss/card.js
- packages/tailwindcss/input.js
- packages/tailwindcss/lib/buttonStyle.js
- packages/tailwindcss/lib/inputStyle.js
- packages/tailwindcss/tab.js
- packages/tailwindcss/tailwind.config.js
- packages/tailwindcss/theme.js
ref: #271 
https://tailwindcss.com/docs/border-color のデフォルト色を変更しそれを尊重するスタイルへと変更します。
この変更により境界線の色がカスタマイズ可能になります。
> feat: 境界線のデフォルト色の変更

- .github/workflows/deploy.yaml
- README.md
- RELEASE_GUIDE.md
- packages/tailwindcss/README.md
- packages/tailwindcss/stories/Introduction.stories.mdx
> chore: develop ブランチの廃止

- .github/release.yaml
- .github/workflows/versionup.yaml
- RELEASE_GUIDE.md
- package.json
- renovate.json
- バージョン変更のための GitHub Actions ワークフローの作成
- リリースノート自動生成のための設定
動作確認は未実施です
問題があれば都度修正します
> chore: リリースワークフローの変更

- packages/tailwindcss/stories/ToggleSwitch.stories.mdx
resolve #311 
label 要素にフレージングコンテンツ（この場合 span 要素）を含む設計
にもかかわらず label 要素に何も含めていない点を修正します
> fix(ToggleSwitch): あやまったマークアップ

- packages/tailwindcss/stories/FilledTag.stories.mdx
- packages/tailwindcss/stories/Tag.stories.mdx
> fix(*Tag): 終了タグを省略すべきでない要素で省略されている

- packages/tailwindcss/stories/FilledTag.stories.mdx
- packages/tailwindcss/stories/IconButton.stories.mdx
- packages/tailwindcss/stories/Input.stories.mdx
- packages/tailwindcss/stories/OutlinedButton.stories.mdx
- packages/tailwindcss/stories/ProfileCard.stories.mdx
- packages/tailwindcss/stories/Select.stories.mdx
- packages/tailwindcss/stories/Tag.stories.mdx
- packages/tailwindcss/stories/TextButton.stories.mdx
- packages/tailwindcss/stories/Textarea.stories.mdx
- packages/tailwindcss/stories/ToggleSwitch.stories.mdx
テンプレートタグ使用時の改行が含まれるかどうかで
整形結果がことなるのを揃える目的
#430 と変更箇所が重複するので、#430  との差分を示すようにしています
> chore: テンプレートタグの整形

- .github/workflows/versionup.yaml
この変更自体に意味はありません
https://github.com/tuqulore/jumpu-ui/issues/432 の検証をする目的を含みます
> chore: GitHub Actions 名称変更

- packages/tailwindcss/stories/Button.stories.mdx
resolve #467 
引用をとりやめて文章内リンクに留めることで
引用にともなう意図しないリンク切れ等を予防します。
> docs: WAI-ARIA button role の説明の更新

- packages/tailwindcss/src/components/accordion.css
- packages/tailwindcss/src/components/tabs.css
- packages/tailwindcss/src/components/toggle-switch.css
> Use pointer default

- packages/docs/.vitepress/config.mts
- packages/docs/playground.md
resolve #https://github.com/tuqulore/jumpu-ui/issues/278
Tailwind Play を使用します
> プレイグラウンドの文書化

- .vscode/extensions.json
- .vscode/settings.json
- packages/docs/tsconfig.json
following https://vitepress.dev/guide/using-vue#vs-code-intellisense-support
> Setup VS Code IntelliSense Settings

- packages/tailwindcss/README.md
Check this: https://github.com/tuqulore/website-boilerplate/pull/795
> We've support `@tailwindcss/postcss`

- packages/tailwindcss/README.md
Please check https://github.com/tuqulore/website-boilerplate/pull/804
> Update for `@tailwindcss/postcss` example

- packages/tailwindcss/package.json
- packages/tailwindcss/src/components/accordion.css
- packages/tailwindcss/src/components/avatar.css
- packages/tailwindcss/src/components/badge.css
- packages/tailwindcss/src/components/boxed-tabs.css
- packages/tailwindcss/src/components/button.css
- packages/tailwindcss/src/components/card.css
- packages/tailwindcss/src/components/filled-tag.css
- packages/tailwindcss/src/components/icon-button.css
- packages/tailwindcss/src/components/input.css
- packages/tailwindcss/src/components/outlined-button.css
- packages/tailwindcss/src/components/select.css
- packages/tailwindcss/src/components/spinner.css
- packages/tailwindcss/src/components/tabs.css
- packages/tailwindcss/src/components/tag.css
- packages/tailwindcss/src/components/text-button.css
- packages/tailwindcss/src/components/textarea.css
- packages/tailwindcss/src/components/toggle-switch.css
- packages/tailwindcss/stylelint.config.mjs
- pnpm-lock.yaml
See https://github.com/stormwarning/stylelint-config-recess-order/tree/v6.0.0
> Setup stylelint-config-recess-order

- packages/tailwindcss/package.json
package.json を参照したいツール等のために出力しておく目的
> Exports package.json

- .github/workflows/versionup.yaml
次に指定するバージョンとの競合を解消します
https://github.com/tuqulore/jumpu-ui/blob/0c4ec74fd085bba0e0203b0e1a7fa1046721ac05/package.json#L25
> fix: Multiple versions of pnpm specified

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/versionup.yaml
- renovate.json
ref https://github.com/tuqulore/office/issues/544
> Setup concurrency and use composite actions
